spring:
  profiles:
    active: local
  application:
    name: boilerplate-internal-api
  config:
    import:
      - 'classpath:boilerplate-service.yml'
      - 'classpath:boilerplate-http.yml'
      - 'classpath:boilerplate-message.yml'
      - 'classpath:boilerplate-persistence.yml'
server:
  tomcat:
    mbeanregistry:
      enabled: true
springdoc:
  api-docs:
    enabled: false
management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          show-components: always
          include:
            - livenessState
        readiness:
          show-components: always
    prometheus:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true


---
spring.config.activate.on-profile: local
springdoc:
  api-docs:
    enabled: true

---
spring.config.activate.on-profile: local-dev,dev
springdoc:
  api-docs:
    enabled: true