name: Build (JIB)
on:
  workflow_call:
    inputs:
      module:
        description: 'App Module'
        type: string
        required: true
      container-image:
        description: 'Container Image'
        type: string
        required: true
      deployment-version:
        description: 'Version'
        type: string
        required: true
permissions:
  id-token: write 
  contents: read
env:
  AWS_REGION: ap-northeast-2
jobs:
  build-jib:
    name: JIB 빌드
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
#      - name: Setup Java 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'corretto'
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ secrets.AWS_ECR_ROLE}}
#          aws-region: ${{ env.AWS_REGION }}
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          gradle-version: 'wrapper'
#          cache-read-only: true
#      - name: Build with Gradle
#        run: |
#          ./gradlew :apps:${{ inputs.module }}:jib \
#            -Djib.to.image=${{ inputs.container-image }} \
#            -Djib.to.tags=${{ inputs.deployment-version }} \
#            -Djib.to.credHelper=ecr-login \
#            -Pversion=${{ inputs.deployment-version }} \
#            --parallel \
#            --stacktrace
